import { Box, Heading, Text, List, ListItem, Divider } from "@chakra-ui/react";

const TermsConditions = () => {
  return (
    <Box
      maxW="900px"
      mx="auto"
      px={{ base: "20px", md: "40px" }}
      py={{ base: "30px", md: "50px" }}
    >
      <Heading mb="10px">Terms and Conditions</Heading>

      <Text fontSize="sm" color="gray.500" mb="30px">
        Last updated: 01 January 2026
      </Text>

      {/* Legal Intro */}
      <Text mb="20px">
        This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules made thereunder. This electronic record is
        generated by a computer system and does not require any physical or
        digital signatures.
      </Text>

      <Text mb="20px">
        These Terms and Conditions (“Terms”) govern your access to and use of the
        website <b>https://www.kreedentials.com</b> (“Website”).
      </Text>

      <Text mb="20px">
        The Website is owned and operated by{" "}
        <b>AVYAYPRATYAY SPORTS LLP</b>, having its registered office at Plot No. 10,
        2nd Floor, Viman Nagar Colony, Secunderabad Viman Nagar Road, Hyderabad,
        Telangana, India – 500016 (hereinafter referred to as “Company”, “we”,
        “us”, or “our”).
      </Text>

      <Divider my="30px" />

      {/* Acceptance */}
      <Heading size="md" mb="15px">
        Acceptance of Terms
      </Heading>

      <Text mb="20px">
        By accessing, browsing, or using the Website, you agree to be bound by
        these Terms, our Privacy Policy, Refund and Cancellation Policy, Return
        and Exchange Policy, and Shipping Policy.
      </Text>

      <Text mb="20px">
        If you do not agree with any part of these Terms, you must immediately
        discontinue use of the Website.
      </Text>

      <Divider my="30px" />

      {/* User Responsibilities */}
      <Heading size="md" mb="15px">
        User Responsibilities
      </Heading>

      <List spacing={3} pl="20px" styleType="disc">
        <ListItem>
          You agree to provide accurate and complete information during account
          creation and checkout.
        </ListItem>
        <ListItem>
          You are responsible for maintaining the confidentiality of your
          account credentials.
        </ListItem>
        <ListItem>
          You shall not use the Website for any unlawful, fraudulent, or
          prohibited activity under Indian law.
        </ListItem>
        <ListItem>
          You agree to pay all applicable charges for purchases made through the
          Website.
        </ListItem>
      </List>

      <Divider my="30px" />

      {/* Payments */}
      <Heading size="md" mb="15px">
        Payments
      </Heading>

      <Text mb="20px">
        All payments on the Website are processed through secure and authorized
        third-party payment gateways. The Company does not store or process any
        card details, UPI credentials, or sensitive payment information.
      </Text>

      <Divider my="30px" />

      {/* Cancellation & Refunds */}
      <Heading size="md" mb="15px">
        Cancellations, Returns and Refunds
      </Heading>

      <Text mb="20px">
  All cancellations, returns, exchanges, and refunds are governed by our
  Refund and Cancellation Policy and Return and Exchange Policy, available
  on the Website, and shall be processed in accordance with applicable
  Indian laws.
</Text>


      <Divider my="30px" />

      {/* Service Availability */}
      <Heading size="md" mb="15px">
        Service Availability
      </Heading>

      <Text mb="20px">
  We reserve the right to modify, suspend, or discontinue any part of the
  Website or services, provided that such changes do not affect confirmed
  orders or payments already made by users, except as permitted under
  applicable law.
</Text>

      <Divider my="30px" />

      {/* Intellectual Property */}
      <Heading size="md" mb="15px">
        Intellectual Property Rights
      </Heading>

      <Text mb="20px">
        All content on the Website including text, images, logos, graphics, and
        software is the intellectual property of AVYAYPRATYAY SPORTS LLP and is
        protected under applicable Indian laws.
      </Text>

      <Divider my="30px" />

      {/* Third Party Links */}
      <Heading size="md" mb="15px">
        Third-Party Links
      </Heading>

      <Text mb="20px">
        The Website may contain links to third-party websites. We are not
        responsible for the content, privacy practices, or policies of such
        websites.
      </Text>

      <Divider my="30px" />

      {/* Force Majeure */}
      <Heading size="md" mb="15px">
        Force Majeure
      </Heading>

      <Text mb="20px">
        The Company shall not be liable for failure to perform its obligations
        due to events beyond reasonable control, including natural disasters,
        government actions, technical failures, or internet disruptions.
      </Text>

      <Divider my="30px" />

      {/* Governing Law */}
      <Heading size="md" mb="15px">
        Governing Law and Jurisdiction
      </Heading>

      <Text mb="20px">
        These Terms shall be governed by and construed in accordance with the
        laws of India. All disputes shall be subject to the exclusive
        jurisdiction of courts in Hyderabad, Telangana.
      </Text>

      <Divider my="30px" />

      {/* Grievance */}
      <Heading size="md" mb="15px">
        Grievance Redressal
      </Heading>

      <Text mb="20px">
        In accordance with the Information Technology Act, 2000 and rules made
        thereunder, the details of the Grievance Officer are provided below.
      </Text>

      <Text>
        <b>Grievance Officer:</b> Aman Goyal <br />
        <b>Email:</b> amangoyal@kreedentials.com <br />
        <b>Phone:</b> +91 7330645588 <br />
        <b>Address:</b> Plot No. 10, 2nd Floor, Viman Nagar Colony, Secunderabad
        Viman Nagar Road, Hyderabad, Telangana, India – 500016 <br />
        <b>Response Time:</b> Within 48 business hours
      </Text>
    </Box>
  );
};

export default TermsConditions;
