import { Box, Heading, Text, List, ListItem, Divider } from "@chakra-ui/react";

const TermsConditions = () => {
  return (
    <Box
      maxW="900px"
      mx="auto"
      px={{ base: "20px", md: "40px" }}
      py={{ base: "30px", md: "50px" }}
    >
      <Heading mb="10px">Terms and Conditions</Heading>

      <Text fontSize="sm" color="gray.500" mb="30px">
        Last updated: {new Date().toLocaleDateString()}
      </Text>

      <Text mb="20px">
        This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules thereunder as applicable and the amended
        provisions pertaining to electronic records in various statutes as
        amended by the Information Technology Act, 2000. This electronic record
        is generated by a computer system and does not require any physical or
        digital signatures.
      </Text>

      <Text mb="20px">
        This document is published in accordance with the provisions of Rule 3
        (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011
        that require publishing the rules and regulations, privacy policy and
        Terms of Use for access or usage of domain name
        https://www.kreedentials.com ("Website"), including the related mobile
        site and mobile application (hereinafter referred to as the "Platform").
      </Text>

      <Text mb="20px">
        The Platform is owned by <b>AVYAYPRATYAY SPORTS LLP</b>, a company
        incorporated under the Companies Act, 1956 with its registered office at
        Plot No. 10, 2nd Floor, Viman Nagar Colony, Secunderabad Viman Nagar Road,
        Hyderabad, India (hereinafter referred to as the "Platform Owner", "we",
        "us", "our").
      </Text>

      <Divider my="30px" />

      <Heading size="md" mb="15px">
        Acceptance of Terms
      </Heading>

      <Text mb="20px">
        Your use of the Platform and services and tools are governed by the
        following terms and conditions ("Terms of Use"). If you transact on the
        Platform, you shall be subject to the policies applicable to such
        transactions. By mere use of the Platform, you shall be contracting with
        the Platform Owner, and these Terms constitute your binding obligations.
      </Text>

      <Text mb="20px">
        These Terms of Use can be modified at any time without assigning any
        reason. It is your responsibility to periodically review these Terms to
        stay informed of updates.
      </Text>

      <Divider my="30px" />

      <Heading size="md" mb="15px">
        User Responsibilities
      </Heading>

      <List spacing={3} pl="20px" styleType="disc">
        <ListItem>
          You agree to provide true, accurate, and complete information during
          registration and are responsible for all activities under your
          account.
        </ListItem>
        <ListItem>
          Your use of the Platform and Services is at your sole risk and
          discretion.
        </ListItem>
        <ListItem>
          You agree not to use the Platform or Services for any unlawful or
          prohibited purpose under Indian or applicable local laws.
        </ListItem>
        <ListItem>
          You agree to pay all charges associated with availing the Services.
        </ListItem>
      </List>

      <Divider my="30px" />

      <Heading size="md" mb="15px">
        Intellectual Property
      </Heading>

      <Text mb="20px">
        The contents of the Platform and the Services are proprietary and
        licensed to the Platform Owner. You shall have no authority to claim any
        intellectual property rights, title, or interest in the content,
        including but not limited to design, layout, look, and graphics.
      </Text>

      <Divider my="30px" />

      <Heading size="md" mb="15px">
        Third-Party Links
      </Heading>

      <Text mb="20px">
        The Platform may contain links to third-party websites. Upon accessing
        these links, you will be governed by the terms, privacy policies, and
        practices of such third parties. These links are provided solely for
        your convenience.
      </Text>

      <Divider my="30px" />

      <Heading size="md" mb="15px">
        Indemnification
      </Heading>

      <Text mb="20px">
        You agree to indemnify and hold harmless the Platform Owner, its
        affiliates, officers, directors, agents, and employees from any claim,
        demand, or penalty arising out of your breach of these Terms, applicable
        laws, or third-party rights.
      </Text>

      <Divider my="30px" />

      <Heading size="md" mb="15px">
        Force Majeure
      </Heading>

      <Text mb="20px">
        The Platform Owner shall not be liable for any failure or delay in
        performance due to events beyond reasonable control, including natural
        disasters, government actions, or technical failures.
      </Text>

      <Divider my="30px" />

      <Heading size="md" mb="15px">
        Governing Law & Jurisdiction
      </Heading>

      <Text mb="20px">
        These Terms shall be governed by and construed in accordance with the
        laws of India. All disputes shall be subject to the exclusive
        jurisdiction of the courts in Hyderabad, Telangana.
      </Text>

      <Divider my="30px" />

      <Heading size="md" mb="15px">
        Contact
      </Heading>

      <Text>
        All concerns or communications relating to these Terms must be
        communicated to us using the contact information provided on this
        website.
      </Text>
    </Box>
  );
};

export default TermsConditions;
