import { Box, Heading, Text, List, ListItem, Divider } from "@chakra-ui/react";

const TermsConditions = () => {
  return (
    <Box
      maxW="900px"
      mx="auto"
      px={{ base: "20px", md: "40px" }}
      py={{ base: "30px", md: "50px" }}
    >
      {/* Title */}
      <Heading mb="10px">Terms and Conditions</Heading>

      {/* Last Updated */}
      <Text fontSize="sm" color="gray.500" mb="30px">
        Last updated: 01 January 2026
      </Text>

      {/* Legal Intro */}
      <Text mb="20px">
        This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules made thereunder as applicable and the
        amended provisions pertaining to electronic records in various statutes
        as amended by the Information Technology Act, 2000. This electronic
        record is generated by a computer system and does not require any
        physical or digital signatures.
      </Text>

      <Text mb="20px">
        This document is published in accordance with the provisions of Rule 3
        (1) of the Information Technology (Intermediaries Guidelines) Rules,
        2011, which require publishing the rules and regulations, privacy policy
        and Terms of Use for access or usage of the domain name{" "}
        <b>https://www.kreedentials.com</b> (the “Website”), including the related
        mobile site and mobile application (collectively referred to as the
        “Platform”).
      </Text>

      <Text mb="20px">
        The Platform is owned and operated by{" "}
        <b>AVYAYPRATYAY SPORTS LLP</b>, a limited liability partnership
        incorporated under the Companies Act, 1956, having its registered office
        at Plot No. 10, 2nd Floor, Viman Nagar Colony, Secunderabad Viman Nagar
        Road, Hyderabad, Telangana, India – 500016 (hereinafter referred to as
        “Platform Owner”, “Company”, “we”, “us”, or “our”).
      </Text>

      <Divider my="30px" />

      {/* Acceptance */}
      <Heading size="md" mb="15px">
        Acceptance of Terms
      </Heading>

      <Text mb="20px">
        Your access to, browsing of, or use of the Platform and Services is
        governed by these Terms and Conditions (“Terms of Use”) along with the
        applicable policies, which are incorporated herein by reference. By
        mere use of the Platform, you shall be contracting with the Platform
        Owner and these Terms constitute a legally binding obligation.
      </Text>

      <Text mb="20px" fontWeight="bold">
        ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
        AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE.
      </Text>

      <Divider my="30px" />

      {/* User Responsibilities */}
      <Heading size="md" mb="15px">
        User Obligations
      </Heading>

      <List spacing={3} pl="20px" styleType="disc">
        <ListItem>
          You agree to provide true, accurate, and complete information during
          registration and checkout.
        </ListItem>
        <ListItem>
          You shall be responsible for all activities carried out through your
          registered account.
        </ListItem>
        <ListItem>
          You agree not to use the Platform or Services for any unlawful,
          illegal, or prohibited purposes under applicable Indian laws.
        </ListItem>
        <ListItem>
          You agree to pay all charges associated with availing the Services.
        </ListItem>
      </List>

      <Divider my="30px" />

      {/* Risk Disclaimer */}
      <Heading size="md" mb="15px">
        Use at Your Own Risk
      </Heading>

      <Text mb="20px">
        Your use of the Platform and Services is solely and entirely at your own
        risk and discretion. The Platform Owner does not warrant the accuracy,
        completeness, performance, or suitability of the information and
        materials offered through the Platform.
      </Text>

      <Divider my="30px" />

      {/* Payments */}
      <Heading size="md" mb="15px">
        Payments
      </Heading>

      <Text mb="20px">
        All payments on the Platform are processed through secure and authorized
        third-party payment gateway providers. The Company does not store,
        process, or retain any sensitive payment information such as card
        details, CVV, or UPI credentials.
      </Text>

      <Divider my="30px" />

      {/* Third Party */}
      <Heading size="md" mb="15px">
        Third-Party Links
      </Heading>

      <Text mb="20px">
        The Platform may contain links to third-party websites. Upon accessing
        such links, you shall be governed by the terms and policies of those
        websites. The Company is not responsible for the content or practices of
        such third-party platforms.
      </Text>

      <Divider my="30px" />

      {/* Indemnity */}
      <Heading size="md" mb="15px">
        Indemnity
      </Heading>

      <Text mb="20px">
        You agree to indemnify and hold harmless the Platform Owner, its
        affiliates, officers, directors, agents, and employees from any claims,
        demands, penalties, or damages arising out of your breach of these
        Terms, applicable laws, or third-party rights.
      </Text>

      <Divider my="30px" />

      {/* Limitation */}
      <Heading size="md" mb="15px">
        Limitation of Liability
      </Heading>

      <Text mb="20px">
        In no event shall the Platform Owner be liable for any indirect,
        incidental, consequential, special, or punitive damages. The maximum
        liability, if any, shall not exceed the amount paid by you for the
        relevant transaction or INR 100 (Rupees One Hundred), whichever is
        lower.
      </Text>

      <Divider my="30px" />

      {/* Force Majeure */}
      <Heading size="md" mb="15px">
        Force Majeure
      </Heading>

      <Text mb="20px">
        The Platform Owner shall not be liable for failure or delay in
        performance due to events beyond reasonable control, including natural
        disasters, government actions, technical failures, or internet
        disruptions.
      </Text>

      <Divider my="30px" />

      {/* Governing Law */}
      <Heading size="md" mb="15px">
        Governing Law and Jurisdiction
      </Heading>

      <Text mb="20px">
        These Terms shall be governed by and construed in accordance with the
        laws of India. All disputes shall be subject to the exclusive
        jurisdiction of the courts in Hyderabad, Telangana.
      </Text>

      <Divider my="30px" />

      {/* Grievance */}
      <Heading size="md" mb="15px">
        Grievance Redressal
      </Heading>

      <Text mb="20px">
        In accordance with the Information Technology Act, 2000, the Grievance
        Officer details are provided below:
      </Text>

      <Text>
        <b>Grievance Officer:</b> Aman Goyal <br />
        <b>Email:</b> amangoyal@kreedentials.com <br />
        <b>Phone:</b> +91 7330645588 <br />
        <b>Address:</b> Plot No. 10, 2nd Floor, Viman Nagar Colony, Secunderabad
        Viman Nagar Road, Hyderabad, Telangana, India – 500016 <br />
        <b>Response Time:</b> Within 48 business hours
      </Text>
    </Box>
  );
};

export default TermsConditions;
